config/routes.rb
Rails.application.routes.draw do

  resources :videos
  devise_for :users
  root to: 'homes#top'
  get "/homes/about" => "homes#about", as: "about"
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
        get :follows, :followers
      end
        resource :relationships, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :name, uniqueness: true

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  # フォローをした、されたの関係
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  
  def follow(user_id)
    followers.create(followed: user_id)
  end
  
  def unfollow
    followers.find_by(followed: user_id).destroy
  end
  
  def following?(user)
    following_users.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/video.rb
class Video < ApplicationRecord
  #「投稿する動画は1回で１つ」
  has_one_attached :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @booknew = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      render "show"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new

  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
   end

private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.created_at
    redirect_to video_path(@video)
  end

  def show
    @video = Video.find(params[:id])
  end

  private

  def video_params
    params.require(:video).permit(:title, :introduction, :video)  #Videoモデルに:videoカラムはありませんが、ここはhas_one_attaches :videoに対応します。
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Dog</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <h7 class="inputname">Title</h7>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <h7 class="inputopinion">Opinion</h7>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
        <%= link_to "Show", user_path(@book) %>|
        <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3 px-5 px-sm-0">
  <div class="row">
    <div class="col-3">
      <%= render "layouts/info", user: @user %>
      <%= render "layouts/new", book: @book %>
    </div>
    <div class="col-8 md-8 offset-md-1">
      <h2>Dogs</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= image_tag book.user.get_profile_image(100,100) %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td id="favorite_btn_<%= book.id %>">
                <%= render "favorites/btn", book: book %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3 px-5 px-sm-0">
  <div class="row">
    <div class="col-3">
      <%= render "layouts/info", user: @book.user %>
      <%= render "layouts/new", book: @booknew %>
    </div>
    <div class="col-8 md-8 offset-md-1">
     <h2>Dog detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to user_path(@book.user) do %><%= image_tag @book.user.get_profile_image(100,100) %><% end %><br>
                <%= link_to @book.user.name, user_path(@book.user) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td id="favorite_btn_<%= @book.id %>">
              <%= render "favorites/btn", book: @book %>
            </td>
            <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger btn-sm" , "data-confirm" => "本当に削除しますか？" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fa-regular fa-heart"></i>
    <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/homes/about.html.erb
<div class="head-container">
  <div class="container">
    <div class="row">
      <div class="mx-auto mt-5 mp-3">
        <h1>Welcome to <strong><i class="fa-solid fa-paw"></i>Dogers</strong>!</h1>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="main-container">
  <div class="image src1"></div>
  <div class="image src2"></div>
  <div class="image src3"></div>
  <div class="row">
    <div class="mx-auto mt-5 col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <strong><i class="fa-solid fa-paw"></i>Dogers</strong>  !!</h1>
      <p>In <strong><i class="fa-solid fa-paw"></i>Dogers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various dogs!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container mt-5">
	<div class="row">
  	<div class="mx-auto">
  		<p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><span>Dogers</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link text-light" do %><i class="fa-solid fa-house"></i> Home
            </li><% end %>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link text-light" do %><i class="fa-solid fa-users"></i> Users
            </li><% end %>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link text-light" do %><i class="fa-solid fa-dog"></i> Dogs
            </li><% end %>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %><i class="fa-solid fa-sign-out-alt"></i> Log out
            </li><% end %>
            <li class="nav-item">
              <%= link_to new_video_path, class: "nav-link text-light" do %><i class="fa-solid fa-photo-film"></i> Video
            </li><% end %>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light" do %><i class="fa-solid fa-house"></i> Home
            </li><% end %>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link text-light" do %><i class="fa-solid fa-link"></i> About
            </li><% end %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %><i class="fa-solid fa-user-plus"></i> Sign up
            </li><% end %>
            <li class="nav-item">
              <%= link_to user_session_path, class: "nav-link text-light" do %><i class="fa-solid fa-sign-in-alt"></i> Log in
            </li><% end %>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
      <th scope="row">name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th scope="row">introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fa-solid fa-user-gear"></i>
<% end %><br>

app/views/layouts/_new.html.erb
<h2>New dog</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/49c651f6bf.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'hogehoge', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/users/_books.html.erb
<h2>Dogs</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th scope="col">Title</th>
      <th scope="col">Opinion</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image(100,100) %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <h7 class="inputname">Name</h7>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <h7 class="inputimage">Image</h7><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group">
          <h7 class="inputIntroduction">Introduction</h7>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-3 px-5 px-sm-0">
  <div class="row">
    <div class="col-3">
      <%= render "layouts/info", user: current_user %>
      <%= render "layouts/new", book: @book %>
    </div>
    <div class="col-8 md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3 px-5 px-sm-0">
  <div class="row">
    <div class="col-3">
      <%= render "layouts/info", user: @user %>
      <%= render "layouts/new", book: @book %>
    </div>
    <div class="col-8 md-8 offset-md-1">
      <%= render "books", book: @books %>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<%= form_with model: @video, local: true do |f| %>
  <p>title</p><%= f.text_field :title %><br>
  <p>introduction</p><%= f.text_area :introduction %><br>
  <p>video</p><%= f.file_field :video %><br>
  <%= f.submit %>
<% end %>

app/views/videos/show.html.erb
<% if @video.video.attached? %>
  <p><%= @video.title %></p><br>
  <p><%= @video.introduction %></p>
  <video src = "<%= rails_blob_path(@video.video) %>" type="video/mp4" controls></video><!-- video_tag @video.video 　と書いてしまうと、データを /app/assets/ の方に探しにいくみたいで、アセットパイプラインのエラーが出ます。-->
  <% if @book.user_id == current_user.id %>
  <td><%= link_to "Edit", edit_video_path(@video.id), class: "btn btn-success btn-sm" %></td>
  <td><%= link_to "Destroy", video_path(@video), method: :delete, class: "btn btn-danger btn-sm" , "data-confirm" => "本当に削除しますか？" %></td>
  <% end %>
<% end %>